{% set version = "0.9.1.47" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64 and arm_variant_type == "sbsa"]
{% set platform = "linux-aarch64" %}  # [aarch64 and arm_variant_type == "tegra"]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}
{% set soname = version.split(".")[0] %}
{% set cuda_major = environ.get("cuda_compiler_version", "13.0").split(".")[0] %}

{% set sha256 = "5803ed38253923578a2ae3b21dabdc963c4effccfed07ca5e1e3acb84ecd1535" %}  # [linux64 and (cuda_compiler_version or "").startswith("12")]
{% set sha256 = "34d482f4145cbdda731e66f8c31e2019385e24274f00892bb112a6523758d11f" %}  # [linux64 and (cuda_compiler_version or "").startswith("13")]
{% set sha256 = "25878f583c9797146aa7b396f8219da23f388780c4fc4f72121300aace9ba1b3" %}  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
{% set sha256 = "4e85e0eec6f08b4300a827e028f4f28c20b641adf361c795569c25947cb19852" %}  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
{% set sha256 = "f732791bae840f84a905544a398856adad2701ea3cb510ee72582c555c700fd4" %}  # [win64 and (cuda_compiler_version or "").startswith("12")]
{% set sha256 = "82f32f3fc416769b64dcce2d605b1bfc0cbc1e3149c19b03f6042f2c99ebd2d1" %}  # [win64 and (cuda_compiler_version or "").startswith("13")]

package:
  name: nvjpeg2000
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/nvjpeg2000/redist/libnvjpeg_2k/{{ platform }}/libnvjpeg_2k-{{ platform }}-{{ version }}_cuda{{ cuda_major }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [osx or ppc64le or cuda_compiler_version in (None, "None")]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]

outputs:

  - name: libnvjpeg2k{{ soname }}
    build:
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libnvjpeg2k.so.*            # [linux]
      - Library\bin\nvjpeg2k*.dll       # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cuda") }}
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_compiler_version }}
      run:
        # Any CUDA within the same major version
        # https://docs.nvidia.com/cuda/nvjpeg2000/userguide.html#prerequisites
        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    test:
      commands:
        - test -L $PREFIX/lib/libnvjpeg2k.so.{{ soname }}                            # [linux]
        - test -f $PREFIX/lib/libnvjpeg2k.so.{{ version }}                           # [linux]
        - if not exist %LIBRARY_BIN%\nvjpeg2k_{{ soname }}.dll exit 1                # [win]
    about:
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      summary: The nvjpeg2k runtume library.
      description: >-
        This is a runtime package only. Developers should install libnvjpeg2k-dev to build with nvjpeg2k.

  - name: libnvjpeg2k-dev
    build:
      run_exports:
        # FIXME: Pin to patch version until 1.0
        - {{ pin_subpackage("libnvjpeg2k" ~ soname, max_pin="x.x.x") }}
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libnvjpeg2k.so                                  # [linux]
      # - lib/pkgconfig/nvjpeg*.pc                          # [linux]
      - include/nvjpeg*                                     # [linux]
      - Library\include\nvjpeg*                             # [win]
      - Library\lib\nvjpeg*.lib                              # [win]
    requirements:
      host:
        - {{ pin_subpackage("libnvjpeg2k" ~ soname, exact=True) }}
        - cuda-version {{ cuda_compiler_version }}
      run:
        - {{ pin_subpackage("libnvjpeg2k" ~ soname, exact=True) }}
        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    test:
      commands:
        - test -L $PREFIX/lib/libnvjpeg2k.so                                    # [linux]
        # - test -f $PREFIX/lib/pkgconfig/nvjpeg*.pc                            # [linux]
        - test -f $PREFIX/include/nvjpeg2k_version.h                            # [linux]
        - test -f $PREFIX/include/nvjpeg2k.h                                    # [linux]
        - if not exist %LIBRARY_INC%\nvjpeg2k_version.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\nvjpeg2k.h exit 1                          # [win]
        - if not exist %LIBRARY_LIB%\nvjpeg2k.lib exit 1                        # [win]

  - name: libnvjpeg2k-static
    build:
      skip: true  # [not linux]
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libnvjpeg2k_static.a
    requirements:
      host:
        - {{ pin_subpackage("libnvjpeg2k-dev", exact=True) }}
        - cuda-version {{ cuda_compiler_version }}
      run:
        - {{ pin_subpackage("libnvjpeg2k-dev", exact=True) }}
        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    test:
      commands:
        - test -f $PREFIX/lib/libnvjpeg2k_static.a
    about:
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      summary: The nvjpeg2k static library.
      description: >-
        This is a static-linking package only. Developers should install libnvjpeg2k-dev to link dynamically with nvjpeg2k.

about:
  home: https://docs.nvidia.com/cuda/nvjpeg2000/
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: The nvJPEG2000 development package.
  description: >-
    The nvJPEG2000 library accelerates the decoding and encoding of JPEG2000 images on NVIDIA GPUs. The library is built on the CUDA platform and is supported on Pascal+ GPU architectures.

  doc_url: https://docs.nvidia.com/cuda/nvjpeg2000/

extra:
  feedstock-name: libnvjpeg2k
  recipe-maintainers:
    - conda-forge/cuda
