{% set version = "0.10.0.49" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64 and arm_variant_type == "sbsa"]
{% set platform = "linux-aarch64" %}  # [aarch64 and arm_variant_type == "tegra"]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}
{% set soname = version.split(".")[0] %}
{% set cuda_major = environ.get("cuda_compiler_version", "13.0").split(".")[0] %}

{% set sha256 = "5803ed38253923578a2ae3b21dabdc963c4effccfed07ca5e1e3acb84ecd1535" %}  # [linux64 and (cuda_compiler_version or "").startswith("12")]
{% set sha256 = "34d482f4145cbdda731e66f8c31e2019385e24274f00892bb112a6523758d11f" %}  # [linux64 and (cuda_compiler_version or "").startswith("13")]
{% set sha256 = "7c0585d538b97aef4c41b126a90c387c0e9d4f18be6166a76c2a264ffc8c1217" %}  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "tegra"]
{% set sha256 = "25878f583c9797146aa7b396f8219da23f388780c4fc4f72121300aace9ba1b3" %}  # [aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
{% set sha256 = "4e85e0eec6f08b4300a827e028f4f28c20b641adf361c795569c25947cb19852" %}  # [aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
{% set sha256 = "f732791bae840f84a905544a398856adad2701ea3cb510ee72582c555c700fd4" %}  # [win64 and (cuda_compiler_version or "").startswith("12")]
{% set sha256 = "82f32f3fc416769b64dcce2d605b1bfc0cbc1e3149c19b03f6042f2c99ebd2d1" %}  # [win64 and (cuda_compiler_version or "").startswith("13")]

package:
  name: nvjpeg2000
  version: {{ version }}

source:
  - url: "https://developer.download.nvidia.com/compute/nvjpeg2000/redist/libnvjpeg_2k/linux-x86_64/libnvjpeg_2k-linux-x86_64-{{ version }}_cuda12-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "b17ec3141ec50e0c3b796d4f28dae8370d8db3684deb849c87fc7ad52be1cbcb"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://developer.download.nvidia.com/compute/nvjpeg2000/redist/libnvjpeg_2k/linux-x86_64/libnvjpeg_2k-linux-x86_64-{{ version }}_cuda13-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "31f52bb363a63089552954b055fbbe84f8ac64e4f9850c9d9a2366338fe15f12"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
  - url: "https://developer.download.nvidia.com/compute/nvjpeg2000/redist/libnvjpeg_2k/linux-sbsa/libnvjpeg_2k-linux-sbsa-{{ version }}_cuda12-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
    sha256: "c8991cb9b26d184407413b860448e0ab8358400341461f602f9a2b3b61291340"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
  - url: "https://developer.download.nvidia.com/compute/nvjpeg2000/redist/libnvjpeg_2k/linux-sbsa/libnvjpeg_2k-linux-sbsa-{{ version }}_cuda13-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
    sha256: "c66c5b8d868d4a4976da5be5eb6ef13080136d6243232f68fee443f8268802f9"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
  - url: "https://developer.download.nvidia.com/compute/nvjpeg2000/redist/libnvjpeg_2k/windows-x86_64/libnvjpeg_2k-windows-x86_64-{{ version }}_cuda12-archive.zip"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "40684ca3f49b1378526c63ddad6552c5865774962f509b4d8a14dcafe740e152"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://developer.download.nvidia.com/compute/nvjpeg2000/redist/libnvjpeg_2k/windows-x86_64/libnvjpeg_2k-windows-x86_64-{{ version }}_cuda13-archive.zip"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "b6e2059fe1a9702d5ac5418aba80207fe83d77e577dba0f011534ed3a6615795"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]
  - url: "https://developer.download.nvidia.com/compute/nvjpeg2000/redist/libnvjpeg_2k/linux-aarch64/libnvjpeg_2k-linux-aarch64-{{ version }}_cuda12-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "tegra"]
    sha256: "e38cf5872a92a5f984a0f370ea2d527da4b9166238ee9a5c423b5289d773dba7"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "tegra"]

build:
  number: 0
  skip: true  # [osx or ppc64le or cuda_compiler_version in (None, "None")]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]

outputs:

  - name: libnvjpeg2k{{ soname }}
    build:
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libnvjpeg2k.so.*            # [linux]
      - Library\bin\nvjpeg2k*.dll       # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cuda") }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [linux and aarch64 and cuda_compiler_version != "None"]
      host:
        - cuda-version {{ cuda_compiler_version }}
      run:
        # Any CUDA within the same major version
        # https://docs.nvidia.com/cuda/nvjpeg2000/userguide.html#prerequisites
        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    test:
      commands:
        - test -L $PREFIX/lib/libnvjpeg2k.so.{{ soname }}                            # [linux]
        - test -f $PREFIX/lib/libnvjpeg2k.so.{{ version }}                           # [linux]
        - if not exist %LIBRARY_BIN%\nvjpeg2k_{{ soname }}.dll exit 1                # [win]
    about:
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      summary: The nvjpeg2k runtume library.
      description: >-
        This is a runtime package only. Developers should install libnvjpeg2k-dev to build with nvjpeg2k.

  - name: libnvjpeg2k-dev
    build:
      run_exports:
        # FIXME: Pin to patch version until 1.0
        - {{ pin_subpackage("libnvjpeg2k" ~ soname, max_pin="x.x.x") }}
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libnvjpeg2k.so                                  # [linux]
      # - lib/pkgconfig/nvjpeg*.pc                          # [linux]
      - include/nvjpeg*                                     # [linux]
      - Library\include\nvjpeg*                             # [win]
      - Library\lib\nvjpeg*.lib                              # [win]
    requirements:
      host:
        - {{ pin_subpackage("libnvjpeg2k" ~ soname, exact=True) }}
        - cuda-version {{ cuda_compiler_version }}
        - arm-variant * {{ arm_variant_type }}  # [linux and aarch64 and cuda_compiler_version != "None"]
      run:
        - {{ pin_subpackage("libnvjpeg2k" ~ soname, exact=True) }}
        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    test:
      commands:
        - test -L $PREFIX/lib/libnvjpeg2k.so                                    # [linux]
        # - test -f $PREFIX/lib/pkgconfig/nvjpeg*.pc                            # [linux]
        - test -f $PREFIX/include/nvjpeg2k_version.h                            # [linux]
        - test -f $PREFIX/include/nvjpeg2k.h                                    # [linux]
        - if not exist %LIBRARY_INC%\nvjpeg2k_version.h exit 1                  # [win]
        - if not exist %LIBRARY_INC%\nvjpeg2k.h exit 1                          # [win]
        - if not exist %LIBRARY_LIB%\nvjpeg2k.lib exit 1                        # [win]

  - name: libnvjpeg2k-static
    build:
      skip: true  # [not linux]
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libnvjpeg2k_static.a
    requirements:
      host:
        - {{ pin_subpackage("libnvjpeg2k-dev", exact=True) }}
        - cuda-version {{ cuda_compiler_version }}
        - arm-variant * {{ arm_variant_type }}  # [linux and aarch64 and cuda_compiler_version != "None"]
      run:
        - {{ pin_subpackage("libnvjpeg2k-dev", exact=True) }}
        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    test:
      commands:
        - test -f $PREFIX/lib/libnvjpeg2k_static.a
    about:
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      summary: The nvjpeg2k static library.
      description: >-
        This is a static-linking package only. Developers should install libnvjpeg2k-dev to link dynamically with nvjpeg2k.

about:
  home: https://docs.nvidia.com/cuda/nvjpeg2000/
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: The nvJPEG2000 development package.
  description: >-
    The nvJPEG2000 library accelerates the decoding and encoding of JPEG2000 images on NVIDIA GPUs. The library is built on the CUDA platform and is supported on Pascal+ GPU architectures.

  doc_url: https://docs.nvidia.com/cuda/nvjpeg2000/

extra:
  feedstock-name: libnvjpeg2k
  recipe-maintainers:
    - conda-forge/cuda
